// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: last_fetched.sql

package database

import (
	"context"
)

const getNextFeedsToFetch = `-- name: GetNextFeedsToFetch :many
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at FROM feeds
    ORDER BY last_fetched_at DESC
    LIMIT 10
`

func (q *Queries) GetNextFeedsToFetch(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getNextFeedsToFetch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedsFetched = `-- name: MarkFeedsFetched :exec
UPDATE feeds 
    SET time_last_fetched = TIMESTAMP
`

func (q *Queries) MarkFeedsFetched(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markFeedsFetched)
	return err
}
